[options]
addons_path = /Users/devanshkashiyani/SOS/odoo/addons,/Users/devanshkashiyani/SOS/custom_addons
db_host = localhost
db_user = devanshkashiyani
db_name = skyline_sa
http_port = 8069
admin_passwd = admin
data_dir = /Users/devanshkashiyani/SOS/.odoo_data
