import { useEffect, useState, type ReactNode } from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import * as AlertPrimitive from '@radix-ui/react-alert-dialog';
import * as TabsPrimitive from '@radix-ui/react-tabs';
import { Slot } from '@radix-ui/react-slot';
import { X, LoaderCircle, ArrowRight, AlertCircle, Search, Inbox, Eye, EyeOff } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ApiError, textStatus, type Row } from '../lib/api';
export function Button({children,variant='primary',asChild=false,...props}:any){const Comp=asChild?Slot:'button';return <Comp className={`button ${variant}`} {...props}>{children}</Comp>;}
export function Badge({status,children}:any){return <span className={`badge ${String(status||'').toLowerCase().replaceAll('_','-')}`}><span className="status-dot"/>{children||textStatus(status)}</span>;}
export function Panel({title,link,linkText='View all',children,className='',icon:Icon}:any){return <section className={`panel ${className}`}>{title&&<div className="panel-heading"><h2>{Icon&&<Icon size={20}/>} {title}</h2>{link&&<Link className="text-link" to={link}>{linkText} <ArrowRight size={15}/></Link>}</div>}{children}</section>;}
export function Header({title,subtitle,children}:any){return <header className="page-header"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div><div className="header-actions">{children}</div></header>;}
export function State({query,children}:any){if(query.isPending)return <div className="state"><LoaderCircle className="spin" size={24}/>Loading your workspace…</div>;if(query.isError)return <div className="state error"><AlertCircle size={24}/><p>{query.error.message}</p><Button variant="outline" onClick={()=>query.refetch()}>Try again</Button></div>;return children;}
export function Empty({children='No records yet.'}:any){return <div className="empty"><Inbox size={28}/><p>{children}</p></div>;}
export function Table({columns,rows,empty}: {columns:{label:string;render:(row:Row)=>ReactNode;className?:string}[];rows:Row[];empty?:string}){return <div className="table-scroll"><table><thead><tr>{columns.map((c,i)=><th key={i} className={c.className}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map((c,j)=><td key={j} className={c.className}>{c.render(r)}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty>{empty}</Empty>}</div>;}
export function Modal({title,description,open,onOpenChange,children}: {title?:ReactNode;description?:ReactNode;open:boolean;onOpenChange:(open:boolean)=>void;children?:ReactNode}){return <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}><DialogPrimitive.Portal><DialogPrimitive.Overlay className="dialog-overlay"/><DialogPrimitive.Content className="dialog-content"><div className="dialog-heading"><DialogPrimitive.Title>{title}</DialogPrimitive.Title><DialogPrimitive.Close className="icon-button" aria-label="Close dialog"><X size={20}/></DialogPrimitive.Close></div><DialogPrimitive.Description className="muted">{description||'Enter the details below and save your changes.'}</DialogPrimitive.Description>{children}</DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>;}
export function Confirm({title,description,children,onConfirm}:any){const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [open,setOpen]=useState(false);return <AlertPrimitive.Root open={open} onOpenChange={setOpen}><AlertPrimitive.Trigger asChild>{children}</AlertPrimitive.Trigger><AlertPrimitive.Portal><AlertPrimitive.Overlay className="dialog-overlay"/><AlertPrimitive.Content className="dialog-content confirm"><AlertPrimitive.Title>{title}</AlertPrimitive.Title><AlertPrimitive.Description className="muted">{description}</AlertPrimitive.Description>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><AlertPrimitive.Cancel asChild><Button variant="outline">Cancel</Button></AlertPrimitive.Cancel><Button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await onConfirm();setOpen(false);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{busy?'Working…':'Confirm'}</Button></div></AlertPrimitive.Content></AlertPrimitive.Portal></AlertPrimitive.Root>;}
export type Field={name:string;label:string;type?:string;required?:boolean;min?:number;max?:number;options?:{value:string;label:string}[];help?:string;integer?:boolean};
export function Form({fields,initial={},onSubmit,label='Save changes',children}: {fields:Field[];initial?:Row;onSubmit:(values:Row)=>Promise<any>;label?:string;children?:ReactNode}){
 const shape:Record<string,z.ZodTypeAny>={};for(const f of fields){let value=z.string();if(f.required)value=value.min(1,'This field is required.');if(f.type==='email')value=value.email('Enter a valid email address.');let validation:any=value;if(f.type==='number')validation=value.refine(s=>s===''&&!f.required || Number.isFinite(Number(s))&&Number(s)>=(f.min??0)&&Number(s)<=(f.max??Number.MAX_SAFE_INTEGER),`Enter a number between ${f.min??0} and ${f.max??'the allowed maximum'}.`);shape[f.name]=validation;}
 const form=useForm<Row>({resolver:zodResolver(z.object(shape)) as any,defaultValues:Object.fromEntries(fields.map(f=>[f.name,String(initial[f.name]??'')]))});const [error,setError]=useState('');const [showPass,setShowPass]=useState<Record<string,boolean>>({});
 return <form className="form" onSubmit={form.handleSubmit(async values=>{setError('');try{await onSubmit(values);}catch(e:any){setError(e.message);if(e instanceof ApiError&&e.fields)for(const [name,msg] of Object.entries(e.fields))form.setError(name,{message:Array.isArray(msg)?msg.join(', '):msg});}})}><div className="form-grid">{fields.map(f=><div className={`field ${f.type==='textarea'?'wide':''}`} key={f.name}><label htmlFor={f.name}>{f.label}{f.required&&<span className="required" aria-hidden="true"> *</span>}</label>{f.options?<select id={f.name} aria-label={f.label} {...form.register(f.name)}><option value="">Select…</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea id={f.name} aria-label={f.label} rows={3} {...form.register(f.name)}/>:f.type==='password'?<div style={{position:'relative',display:'flex',alignItems:'center',width:'100%'}}><input id={f.name} aria-label={f.label} type={showPass[f.name]?'text':'password'} style={{paddingRight:'2.4rem',width:'100%'}} {...form.register(f.name)}/><button type="button" onClick={()=>setShowPass(s=>({...s,[f.name]:!s[f.name]}))} style={{position:'absolute',right:'0.5rem',background:'none',border:'none',cursor:'pointer',color:'#64748b',padding:'3px',display:'flex',alignItems:'center'}} aria-label={showPass[f.name]?'Hide password':'Show password'}>{showPass[f.name]?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>:<input id={f.name} aria-label={f.label} type={f.type||'text'} step={f.type==='number'?'0.01':undefined} min={f.min} max={f.max} {...form.register(f.name)}/>}<span className="field-help">{f.help}</span>{form.formState.errors[f.name]&&<span className="form-error">{String(form.formState.errors[f.name]?.message)}</span>}</div>)}</div>{children}{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Button type="submit" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting?<><LoaderCircle size={16} className="spin"/> Saving…</>:label}</Button></div></form>;
}
export function Toolbar({search,onSearch,children}:any){return <div className="toolbar"><div className="search"><Search size={17}/><input aria-label="Search records" value={search} onChange={e=>onSearch(e.target.value)} placeholder="Search records…"/></div>{children}</div>;}
export function Pagination({count,page,setPage,size=10}:any){const pages=Math.ceil(count/size);if(pages<=1)return null;return <div className="pagination"><span>{count} records · Page {page} of {pages}</span><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" disabled={page>=pages} onClick={()=>setPage(page+1)}>Next</Button></div>;}
export function useFilter(rows:Row[],keys:string[]){const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(1);useEffect(()=>{setPage(1);},[search,status]);const filtered=rows.filter(r=>(!status||r.status===status)&&keys.some(k=>String(r[k]||'').toLowerCase().includes(search.toLowerCase())));return {search,setSearch,status,setStatus,page,setPage,filtered,paged:filtered.slice((page-1)*10,page*10)};}
export function Tabs({items,value,onValueChange}:any){return <TabsPrimitive.Root value={value} onValueChange={onValueChange}><TabsPrimitive.List className="tabs-list">{items.map((i:any)=><TabsPrimitive.Trigger className="tab" value={i.value} key={i.value}>{i.label}</TabsPrimitive.Trigger>)}</TabsPrimitive.List>{items.map((i:any)=><TabsPrimitive.Content className="tab-content" value={i.value} key={i.value}>{i.content}</TabsPrimitive.Content>)}</TabsPrimitive.Root>;}
export function Notice({children,type='info'}:any){return <div className={`notice ${type}`}><AlertCircle size={17}/><span>{children}</span></div>;}
