import { useEffect, useState, type FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Plus, FileText, Paperclip, Download, Package, ShoppingBag, Mail, Megaphone, Check, Pencil, RotateCcw, ArrowDown, ArrowUp, Wallet, Clock } from 'lucide-react';
import { api, useData, refresh, money, date, toLocal, toUtc, rupees, textStatus, type Row } from '../lib/api';
import { Header, Panel, Button, Badge, Form, Modal, Confirm, Table, State, Toolbar, Pagination, useFilter, Tabs, Notice, Empty, type Field } from '../components/ui';
import { useAuth } from '../App';
import { Metric } from './dashboards';

const methods = [{ value: 'cash', label: 'Cash' }, { value: 'upi', label: 'UPI' }, { value: 'card', label: 'Card' }, { value: 'bank', label: 'Bank' }];
const options = (rows: Row[], field = 'name') => rows.map(row => ({ value: row.id, label: row[field] }));
const editable = (claim: Row) => ['DRAFT', 'CHANGES_REQUESTED'].includes(claim.status);
const paymentFields: Field[] = [{ name: 'method', label: 'Payment method', required: true, options: methods }, { name: 'reference', label: 'Payment reference' }];

export function ClaimEditor({ open, onOpenChange, claim }: { open: boolean; onOpenChange: (open: boolean) => void; claim?: Row | null }) {
  const { user } = useAuth();
  const events = useData<Row[]>('/events', open);
  const tasks = useData<Row[]>('/tasks', open);
  const [files, setFiles] = useState<File[]>([]);
  const [saved, setSaved] = useState<Row | null>(null);
  useEffect(() => { if (open) { setSaved(claim || null); setFiles([]); } }, [open, claim?.id]);
  const ownTasks = (tasks.data || []).filter(task => task.assignee_id === user?.id);
  const eligibleEvents = (events.data || []).filter(event => event.assigned || ownTasks.some(task => task.event_id === event.id) || user?.roles.includes('admin'));
  return <Modal open={open} onOpenChange={onOpenChange} title={claim ? 'Edit expense claim' : 'Submit an expense'} description="Save your purchase as a draft or attach receipts and submit it for review.">
    {open && <Form key={claim?.id || 'new'} label="Save claim" initial={claim ? { ...claim, amount: Number(claim.amount_paise) / 100, save_action: 'draft' } : { category: 'supplies', save_action: 'draft' }} fields={[
      { name: 'description', label: 'Description', required: true }, { name: 'category', label: 'Category', required: true, options: ['supplies', 'printing', 'travel', 'refreshments', 'operations', 'other'].map(value => ({ value, label: textStatus(value) })) },
      { name: 'amount', label: 'Amount (INR)', type: 'number', required: true, min: 0.01 }, { name: 'event_id', label: 'Assigned event (optional)', options: options(eligibleEvents, 'title') },
      { name: 'task_id', label: 'Your task (optional)', options: options(ownTasks, 'title') }, { name: 'save_action', label: 'Next step', required: true, options: [{ value: 'draft', label: 'Save draft' }, { value: 'submit', label: 'Submit for review' }] }
    ]} onSubmit={async values => {
      const payload = { description: values.description, category: values.category, amount_paise: rupees(values.amount), event_id: values.event_id || null, task_id: values.task_id || null };
      let current = await api<Row>(saved?.id ? `/claims/${saved.id}` : '/claims', saved?.id ? 'PATCH' : 'POST', payload);
      setSaved(current);
      try {
        if (files.length) {
          const upload = new FormData(); files.forEach(file => upload.append('files', file));
          current = await api<Row>(`/claims/${current.id}/receipts`, 'POST', upload); setSaved(current); setFiles([]);
        }
        if (values.save_action === 'submit') { await api(`/claims/${current.id}/submit`, 'POST', {}); }
        onOpenChange(false);
      } finally { await refresh(); }
    }}>
      <div className="upload-field"><label htmlFor="claim-receipts"><Paperclip size={17} /> Receipt attachments</label><input id="claim-receipts" type="file" multiple accept="image/jpeg,image/png,application/pdf" onChange={event => setFiles(Array.from(event.target.files || []))} /><p className="field-help">JPEG, PNG or PDF · up to 5 MB each · at most 5 files per claim.</p>{files.map(file => <span className="file-chip" key={file.name}>{file.name}</span>)}</div>
      {!!saved?.receipts?.length && <ReceiptList receipts={saved.receipts} />}
      {saved && <Notice>Your draft is saved. You can finish attaching evidence and submit it here.</Notice>}
    </Form>}
  </Modal>;
}

function ReceiptList({ receipts, onRemove }: { receipts: Row[]; onRemove?: (receipt: Row) => Promise<void> }) {
  return <div className="receipt-list">{receipts.map(receipt => <div className="receipt-item" key={receipt.id}><span className="attention-icon indigo"><FileText size={20} /></span><div className="flex-grow"><a className="text-link" href={`/api/v1/receipts/${receipt.id}`} target="_blank" rel="noreferrer">{receipt.original_name} <Download size={15} /></a><span className="cell-sub">{Math.ceil(receipt.size_bytes / 1024)} KB · {receipt.mime_type}</span></div>{onRemove && <Confirm title="Remove this receipt?" description="You can attach a replacement while the claim is editable." onConfirm={() => onRemove(receipt)}><Button variant="ghost">Remove</Button></Confirm>}</div>)}{!receipts.length && <Empty>No receipts attached.</Empty>}</div>;
}

export function ClaimsPage({ volunteer = false }: { volunteer?: boolean }) {
  const { user } = useAuth();
  const q = useData<Row[]>('/claims');
  const rows = (q.data || []).filter(row => !volunteer || row.user_id === user?.id);
  const filter = useFilter(rows, ['description', 'category', 'user_name', 'event_name']);
  const [edit, setEdit] = useState<Row | null | undefined>();
  const [selected, setSelected] = useState<Row | null>(null);
  const [action, setAction] = useState('');
  const [message, setMessage] = useState('');
  const detail = useData<Row>(`/claims/${selected?.id}`, !!selected);
  const claim = detail.data;
  return <><Header title={volunteer ? 'My expenses' : 'Reimbursements'} subtitle={volunteer ? 'Your receipts, review notes and reimbursement history.' : 'Review claims and record verified reimbursement payments.'}>{volunteer && <Button onClick={() => setEdit(null)}><Plus size={18} /> Submit expense</Button>}</Header>
    {message && <Notice>{message}</Notice>}<Panel><Toolbar search={filter.search} onSearch={filter.setSearch}><select aria-label="Claim status" value={filter.status} onChange={event => filter.setStatus(event.target.value)}><option value="">All statuses</option>{['DRAFT', 'SUBMITTED', 'CHANGES_REQUESTED', 'REJECTED', 'APPROVED_UNPAID', 'PAID'].map(status => <option key={status} value={status}>{textStatus(status)}</option>)}</select></Toolbar><State query={q}><Table rows={filter.paged} columns={[
      { label: 'Claim', render: row => <div><strong>{row.description}</strong><span className="cell-sub">{volunteer ? date(row.created_at) : row.user_name}</span></div> }, { label: 'Event', render: row => row.event_name || 'Association operations' }, { label: 'Amount', render: row => <strong>{money(row.amount_paise)}</strong> }, { label: 'Status', render: row => <Badge status={row.status} /> }, { label: 'Review note', render: row => <span className="muted">{row.review_note || '—'}</span> }, { label: '', render: row => <Button variant="outline" onClick={() => { setSelected(row); setAction(''); }}>View claim</Button> }
    ]} /><Pagination count={filter.filtered.length} page={filter.page} setPage={filter.setPage} /></State></Panel>
    <ClaimEditor open={edit !== undefined} onOpenChange={open => !open && setEdit(undefined)} claim={edit} />
    <Modal open={!!selected} onOpenChange={open => !open && setSelected(null)} title={selected?.description || 'Expense claim'} description="Evidence and cash settlement are preserved with this claim."><State query={detail}>{claim && <>
      <div className="claim-summary"><div><span className="muted">{claim.user_name || user?.name}</span><h2>{money(claim.amount_paise)}</h2></div><Badge status={claim.status} /></div><div className="detail-facts"><div><span>Event</span><strong>{claim.event_name || 'Association operations'}</strong></div><div><span>Category</span><strong>{textStatus(claim.category)}</strong></div><div><span>Created</span><strong>{date(claim.created_at, true)}</strong></div></div>
      {claim.review_note && <Notice type={claim.status === 'REJECTED' ? 'warning' : 'info'}>{claim.review_note}</Notice>}
      <h3 className="section-label">Receipts</h3><ReceiptList receipts={claim.receipts || []} onRemove={claim.user_id === user?.id && editable(claim) ? async receipt => { await api(`/receipts/${receipt.id}`, 'DELETE'); await refresh(); } : undefined} />
      <div className="action-row">{claim.user_id === user?.id && editable(claim) && <><Button variant="outline" onClick={() => { setEdit(claim); setSelected(null); }}>Edit / attach receipts</Button><Confirm title="Submit this claim for review?" description="The amount and receipts become read-only after submission. Submission does not change cash." onConfirm={async () => { await api(`/claims/${claim.id}/submit`, 'POST', {}); await refresh(); }}><Button>Submit for review</Button></Confirm></>}{!volunteer && claim.status === 'SUBMITTED' && <><Button onClick={() => setAction('approve')}>Approve</Button><Button variant="outline" onClick={() => setAction('request_changes')}>Request corrections</Button><Button variant="danger" onClick={() => setAction('reject')}>Reject</Button></>}{!volunteer && claim.status === 'APPROVED_UNPAID' && <Button onClick={() => setAction('pay')}>Record payment</Button>}</div>
      {action && <div className="action-form"><Notice>{action === 'pay' ? 'Local demo settlement is simulated. Recording this payment posts one outgoing cash entry; no bank transfer is initiated.' : action === 'approve' ? 'Approval records an unpaid obligation. Cash changes only when a payment is recorded.' : 'Explain the correction or rejection so the claimant can understand the decision.'}</Notice><Form key={action} label={action === 'pay' ? 'Record simulated payment' : textStatus(action)} fields={action === 'pay' ? paymentFields : [{ name: 'note', label: 'Review note', type: 'textarea', required: action !== 'approve' }]} onSubmit={async values => { await api(`/claims/${claim.id}/${action === 'pay' ? 'pay' : 'review'}`, 'POST', action === 'pay' ? values : { action, note: values.note }); await refresh(); setAction(''); setMessage(action === 'pay' ? 'Payment recorded once in the cash ledger.' : 'Claim review saved.'); }} /></div>}
      <h3 className="section-label">Payment history</h3><Table rows={claim.payment_history || []} columns={[{ label: 'Recorded', render: row => date(row.created_at, true) }, { label: 'Amount', render: row => money(row.amount_paise) }, { label: 'Method', render: row => textStatus(row.method) }, { label: 'Reference', render: row => row.reference || '—' }, { label: 'Settlement', render: row => <Badge status={row.settlement_kind === 'mock' ? 'SIMULATED' : 'MANUAL'} /> }]} />
    </>}</State></Modal></>;
}

function ProductEditor({ open, onOpenChange, product }: { open: boolean; onOpenChange: (open: boolean) => void; product?: Row | null }) {
  return <Modal open={open} onOpenChange={onOpenChange} title={product ? 'Edit product' : 'Add merchandise'} description="Prices apply to new sales. Existing order line prices are retained.">{open && <Form initial={product ? { ...product, price: Number(product.price_paise) / 100, member_price: Number(product.member_price_paise) / 100, active: String(!!product.active) } : { price: '650', member_price: '500', active: 'true', S: '0', M: '0', L: '0', XL: '0' }} fields={[
    { name: 'name', label: 'Product name', required: true }, { name: 'price', label: 'Standard price (INR)', type: 'number', required: true, min: 0.01 }, { name: 'member_price', label: 'Active member price (INR)', type: 'number', required: true, min: 0.01 }, { name: 'active', label: 'Product status', required: true, options: [{ value: 'true', label: 'Active' }, { value: 'false', label: 'Inactive' }] }, { name: 'description', label: 'Description', type: 'textarea' }, ...(!product ? ['S', 'M', 'L', 'XL'].map(size => ({ name: size, label: `${size} opening stock`, type: 'number', required: true, min: 0, integer: true })) : [])
  ]} onSubmit={async values => { await api(product ? `/products/${product.id}` : '/products', product ? 'PATCH' : 'POST', { name: values.name, description: values.description, price_paise: rupees(values.price), member_price_paise: rupees(values.member_price), active: values.active === 'true', ...(!product ? { variants: ['S', 'M', 'L', 'XL'].map(size => ({ size, stock: Number(values[size]) })) } : {}) }); await refresh(); onOpenChange(false); }} />}</Modal>;
}

function OrderEditor({ open, onOpenChange, products, members }: { open: boolean; onOpenChange: (open: boolean) => void; products: Row[]; members: Row[] }) {
  const [lines, setLines] = useState([{ variant_id: '', quantity: '1' }]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (open) { setLines([{ variant_id: '', quantity: '1' }]); setError(''); } }, [open]);
  const variants = products.filter(product => product.active).flatMap(product => (product.variants || []).map((variant: Row) => ({ ...variant, label: `${product.name} · ${variant.size} · ${variant.stock} in stock`, price_paise: product.price_paise, member_price_paise: product.member_price_paise })));
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = new FormData(event.currentTarget); setBusy(true); setError(''); try { await api('/orders', 'POST', { buyer_name: values.get('buyer_name'), member_id: values.get('member_id') || null, method: values.get('method'), reference: values.get('reference') || '', items: lines.map(line => ({ variant_id: line.variant_id, quantity: Number(line.quantity) })) }); await refresh(); onOpenChange(false); } catch (failure: any) { setError(failure.message); } finally { setBusy(false); } };
  return <Modal open={open} onOpenChange={onOpenChange} title="Record counter sale" description="Stock, historical prices and the cash entry are recorded together."><Notice>Local demo payments are simulated. The server applies active membership benefits and checks remaining stock.</Notice><form className="form" onSubmit={submit}><div className="form-grid"><div className="field"><label htmlFor="buyer-name">Buyer name *</label><input id="buyer-name" name="buyer_name" required minLength={2} /></div><div className="field"><label htmlFor="order-member">Member (optional)</label><select id="order-member" name="member_id"><option value="">Non-member</option>{members.filter(member => !member.archived).map(member => <option key={member.id} value={member.id}>{member.name} · {textStatus(member.membership_status)}</option>)}</select></div></div><div className="order-lines">{lines.map((line, index) => <div className="order-line" key={index}><div className="field flex-grow"><label htmlFor={`variant-${index}`}>Product / size *</label><select id={`variant-${index}`} required value={line.variant_id} onChange={event => setLines(lines.map((current, currentIndex) => currentIndex === index ? { ...current, variant_id: event.target.value } : current))}><option value="">Select variant</option>{variants.map(variant => <option key={variant.id} value={variant.id} disabled={!variant.stock}>{variant.label} · {money(variant.price_paise)}</option>)}</select></div><div className="field quantity-field"><label htmlFor={`quantity-${index}`}>Quantity *</label><input id={`quantity-${index}`} type="number" min="1" max="100" step="1" required value={line.quantity} onChange={event => setLines(lines.map((current, currentIndex) => currentIndex === index ? { ...current, quantity: event.target.value } : current))} /></div>{lines.length > 1 && <Button type="button" variant="ghost" onClick={() => setLines(lines.filter((_, currentIndex) => currentIndex !== index))}>Remove</Button>}</div>)}</div><Button type="button" variant="outline" onClick={() => setLines([...lines, { variant_id: '', quantity: '1' }])}><Plus size={15} /> Add line</Button><div className="form-grid"><div className="field"><label htmlFor="order-method">Payment method *</label><select id="order-method" name="method" required><option value="">Select method</option>{methods.map(method => <option key={method.value} value={method.value}>{method.label}</option>)}</select></div><div className="field"><label htmlFor="order-reference">Reference</label><input id="order-reference" name="reference" /></div></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Button disabled={busy}>{busy ? 'Recording…' : 'Record simulated sale'}</Button></div></form></Modal>;
}

export function ShopPage() {
  const products = useData<Row[]>('/products'); const orders = useData<Row[]>('/orders'); const history = useData<Row[]>('/stock-adjustments'); const members = useData<Row[]>('/members');
  const [tab, setTab] = useState('products'); const [edit, setEdit] = useState<Row | null | undefined>(); const [order, setOrder] = useState(false); const [adjust, setAdjust] = useState<Row | null>(null); const [variantProduct, setVariantProduct] = useState<Row | null>(null); const [error, setError] = useState('');
  const filter = useFilter(products.data || [], ['name', 'description']); const orderFilter = useFilter(orders.data || [], ['buyer_name', 'id']);
  return <><Header title="Shop & inventory" subtitle="Merchandise, size-specific stock and manual counter sales."><Button variant="outline" onClick={() => setEdit(null)}><Plus size={17} /> Add product</Button><Button onClick={() => setOrder(true)}><ShoppingBag size={18} /> Record sale</Button></Header>{error && <Notice type="warning">{error}</Notice>}<Tabs value={tab} onValueChange={setTab} items={[
    { value: 'products', label: 'Products & sizes', content: <Panel><Toolbar search={filter.search} onSearch={filter.setSearch} /><State query={products}><div className="product-grid">{filter.paged.map(product => <article className="product-card" key={product.id}><div className="product-art"><Package size={52} strokeWidth={1.5} /><Badge status={product.active ? 'ACTIVE' : 'INACTIVE'} /></div><div className="product-details"><div className="product-title"><h2>{product.name}</h2><Button variant="ghost" aria-label={`Edit ${product.name}`} onClick={() => setEdit(product)}><Pencil size={17} /></Button></div><p className="muted">{product.description || 'Skyline club merchandise'}</p><div className="product-prices"><strong>{money(product.price_paise)}</strong><span>Member {money(product.member_price_paise)}</span></div><div className="variant-list">{(product.variants || []).map((variant: Row) => <button className={`variant-chip ${variant.stock === 0 ? 'sold-out' : variant.stock <= 5 ? 'low-stock' : ''}`} key={variant.id} onClick={() => setAdjust({ ...variant, product_name: product.name })} aria-label={`Adjust ${product.name} size ${variant.size}, ${variant.stock} in stock`}><strong>{variant.size}</strong><span>{variant.stock ? `${variant.stock} left` : 'Sold out'}</span></button>)}</div>{(product.variants || []).length < 4 && <Button variant="outline" onClick={() => setVariantProduct(product)}>Add size</Button>}<p className="small muted">Select a size to adjust stock with a reason.</p></div></article>)}</div>{!filter.paged.length && <Empty>No products match your search.</Empty>}<Pagination count={filter.filtered.length} page={filter.page} setPage={filter.setPage} /></State></Panel> },
    { value: 'orders', label: 'Order history', content: <Panel><Toolbar search={orderFilter.search} onSearch={orderFilter.setSearch} /><State query={orders}><Table rows={orderFilter.paged} columns={[{ label: 'Buyer / order', render: row => <div><strong>{row.buyer_name}</strong><span className="cell-sub">{date(row.created_at, true)}</span></div> }, { label: 'Items · historical prices', render: row => <div>{(row.items || []).map((item: Row) => <div key={item.id}>{item.product_name} {item.size} × {item.quantity} <span className="muted">@ {money(item.unit_price_paise)}</span></div>)}</div> }, { label: 'Total', render: row => money(row.total_paise) }, { label: 'Collection', render: row => <Badge status={row.collected ? 'COLLECTED' : 'UNCOLLECTED'} /> }, { label: '', render: row => <Button variant="outline" onClick={async () => { setError(''); try { await api(`/orders/${row.id}`, 'PATCH', { collected: !row.collected }); await refresh(); } catch (failure: any) { setError(failure.message); } }}>{row.collected ? 'Mark uncollected' : 'Mark collected'}</Button> }]} /><Pagination count={orderFilter.filtered.length} page={orderFilter.page} setPage={orderFilter.setPage} /></State></Panel> },
    { value: 'history', label: 'Stock history', content: <Panel title="Stock movement history"><State query={history}><Table rows={history.data || []} columns={[{ label: 'Date', render: row => date(row.created_at, true) }, { label: 'Product / size', render: row => `${row.product_name} · ${row.size}` }, { label: 'Change', render: row => <strong className={row.quantity < 0 ? 'negative' : 'positive'}>{row.quantity > 0 ? '+' : ''}{row.quantity}</strong> }, { label: 'Reason', render: row => row.reason }]} /></State></Panel> }
  ]} /><ProductEditor open={edit !== undefined} onOpenChange={open => !open && setEdit(undefined)} product={edit} /><OrderEditor open={order} onOpenChange={setOrder} products={products.data || []} members={members.data || []} />
    <Modal open={!!adjust} onOpenChange={open => !open && setAdjust(null)} title={`Adjust stock · ${adjust?.product_name || ''} ${adjust?.size || ''}`} description={`Current stock: ${adjust?.stock || 0}. Every adjustment is recorded in history.`}>{adjust && <Form fields={[{ name: 'quantity', label: 'Quantity change', type: 'number', min: -100000, max: 100000, integer: true, required: true, help: 'Positive to add stock, negative to remove. Zero is not an adjustment.' }, { name: 'reason', label: 'Reason', type: 'textarea', required: true }]} onSubmit={async values => { await api('/stock-adjustments', 'POST', { variant_id: adjust.id, quantity: Number(values.quantity), reason: values.reason }); await refresh(); setAdjust(null); }} />}</Modal>
    <Modal open={!!variantProduct} onOpenChange={open => !open && setVariantProduct(null)} title="Add product size" description="Opening stock creates a stock history entry.">{variantProduct && <Form initial={{ stock: '0' }} fields={[{ name: 'size', label: 'Size', required: true, options: ['S', 'M', 'L', 'XL'].filter(size => !variantProduct.variants?.some((variant: Row) => variant.size === size)).map(value => ({ value, label: value })) }, { name: 'stock', label: 'Opening stock', type: 'number', integer: true, required: true, min: 0 }]} onSubmit={async values => { await api(`/products/${variantProduct.id}/variants`, 'POST', { size: values.size, stock: Number(values.stock) }); await refresh(); setVariantProduct(null); }} />}</Modal></>;
}

export function FinancePage() {
  const [searchParams, setSearchParams] = useSearchParams(); const [period, setPeriod] = useState('all'); const [category, setCategory] = useState(''); const [direction, setDirection] = useState(''); const [action, setAction] = useState(''); const [reversal, setReversal] = useState<Row | null>(null);
  const eventId = searchParams.get('event') || ''; const eventQuery = eventId ? `&event_id=${encodeURIComponent(eventId)}` : '';
  const summary = useData<Row>(`/finance/summary?period=${period}${eventQuery}`); const transactions = useData<Row[]>(`/finance/transactions?period=${period}${eventQuery}`); const events = useData<Row[]>('/events');
  const filter = useFilter(transactions.data || [], ['description', 'category', 'reference']); const rows = filter.filtered.filter(row => (!category || row.category === category) && (!direction || row.direction === direction)); const d = summary.data || {}; const reversed = new Set((transactions.data || []).map(row => row.reversal_of).filter(Boolean));
  return <><Header title="Finance" subtitle="Settled balance, outstanding obligations and an append-only ledger."><a className="button outline" href={`/api/v1/finance/export.csv?period=${period}${eventQuery}`}><Download size={17} /> Export CSV</a><Button variant="outline" onClick={() => setAction('income')}><Plus size={17} /> Record income</Button><Button onClick={() => setAction('expense')}>Record direct expense</Button></Header><div className="finance-filters"><select aria-label="Reporting period" value={period} onChange={event => setPeriod(event.target.value)}><option value="all">All records</option><option value="month">This month</option><option value="year">This year</option></select><select aria-label="Report by event" value={eventId} onChange={event => { const next = new URLSearchParams(searchParams); if (event.target.value) next.set('event', event.target.value); else next.delete('event'); setSearchParams(next); }}><option value="">All organization events</option>{(events.data || []).map(event => <option key={event.id} value={event.id}>{event.title}</option>)}</select></div><State query={summary}><div className="metrics-grid admin-metrics"><Metric label="Balance received" value={money(d.cash_received_paise)} icon={ArrowDown} tone="green" /><Metric label="Balance paid" value={money(d.cash_paid_paise)} icon={ArrowUp} tone="red" /><Metric label="Available balance" value={money(d.cash_balance_paise)} icon={Wallet} tone="blue" /><Metric label="Approved · unpaid" value={money(d.approved_unpaid_paise)} icon={Clock} tone="amber" /></div><div className="financial-notes"><span>Opening balance <strong>{money(d.opening_cash_paise)}</strong></span><span>Unpaid membership dues <strong>{money(d.unpaid_dues_paise)}</strong></span><span>Submitted claims <strong>{money(d.pending_claims_paise)}</strong></span></div><p className="balance-note">{d.balance_explanation ? d.balance_explanation.replace(/cash/gi, 'balance').replace(/Cash/gi, 'Balance') : 'Available balance = opening balance + settled inflows − settled outflows. Outstanding dues and claims are separate.'}</p></State>
    <Panel title="Transaction history"><Toolbar search={filter.search} onSearch={filter.setSearch}><select aria-label="Transaction category" value={category} onChange={event => { setCategory(event.target.value); filter.setPage(1); }}><option value="">All categories</option>{Array.from(new Set((transactions.data || []).map(row => row.category))).map(value => <option key={value} value={value}>{textStatus(value)}</option>)}</select><select aria-label="Transaction direction" value={direction} onChange={event => { setDirection(event.target.value); filter.setPage(1); }}><option value="">Incoming & outgoing</option><option value="IN">Incoming</option><option value="OUT">Outgoing</option></select></Toolbar><State query={transactions}><Table rows={rows.slice((filter.page - 1) * 10, filter.page * 10)} columns={[{ label: 'Activity', render: row => <div><strong>{row.description}</strong><span className="cell-sub">{date(row.occurred_at, true)} · {textStatus(row.method)} {row.reference && `· ${row.reference}`}</span></div> }, { label: 'Category', render: row => <Badge status={row.category} /> }, { label: 'Settlement', render: row => <Badge status={row.settlement_kind === 'mock' ? 'SIMULATED' : 'MANUAL'} /> }, { label: 'Amount', className: 'right', render: row => <strong className={row.direction === 'IN' ? 'positive' : 'negative'}>{row.direction === 'IN' ? '+ ' : '− '}{money(row.amount_paise)}</strong> }, { label: 'Correction', render: row => row.reversal_of ? <span className="muted">Linked reversal</span> : reversed.has(row.id) ? <Badge status="REVERSED" /> : <Button variant="ghost" onClick={() => setReversal(row)}><RotateCcw size={14} /> Reverse</Button> }]} /><Pagination count={rows.length} page={filter.page} setPage={filter.setPage} /></State></Panel>
    <Modal open={!!action} onOpenChange={open => !open && setAction('')} title={action === 'income' ? 'Record manual income' : 'Record direct expense'} description="Record a confirmed manual balance movement with an audit trail."><Notice>{action === 'expense' ? 'For purchases reimbursed to a volunteer, use their claim payment. Recording the same purchase here would count it twice.' : 'Record balance already received for fundraisers or other income. Dues, tickets and merchandise use their own workflows.'} Local demo settlement is simulated.</Notice>{action && <Form key={action} label="Record simulated settlement" initial={{ category: action === 'income' ? 'fundraiser' : 'operations' }} fields={[{ name: 'description', label: 'Description / notes', required: true, type: 'textarea' }, { name: 'category', label: 'Category', required: true, options: (action === 'income' ? ['fundraiser', 'other'] : ['operations', 'supplies', 'printing', 'travel', 'refreshments', 'other']).map(value => ({ value, label: textStatus(value) })) }, { name: 'amount', label: 'Amount (INR)', required: true, type: 'number', min: 0.01 }, { name: 'event_id', label: 'Event (optional)', options: options(events.data || [], 'title') }, { name: 'date', label: 'Occurred at (optional)', type: 'datetime-local' }, ...paymentFields]} onSubmit={async values => { await api(`/finance/${action}`, 'POST', { description: values.description, category: values.category, amount_paise: rupees(values.amount), event_id: values.event_id || null, ...(values.date ? { date: toUtc(values.date) } : {}), method: values.method, reference: values.reference }); await refresh(); setAction(''); }} />}</Modal>
    <Modal open={!!reversal} onOpenChange={open => !open && setReversal(null)} title="Record linked reversal" description="The original record stays in the ledger. One opposite balance entry records the full correction.">{reversal && <><Notice type="warning">Reverse {money(reversal.amount_paise)} for “{reversal.description}” only after confirming the correcting balance movement. Ticket refund execution and partial refunds are deferred.</Notice><Form fields={[{ name: 'reason', label: 'Reason', required: true, type: 'textarea' }]} label="Record full reversal" onSubmit={async values => { await api(`/finance/transactions/${reversal.id}/reverse`, 'POST', values); await refresh(); setReversal(null); }} /></>}</Modal></>;
}

export function AnnouncementsPage({ volunteer = false }: { volunteer?: boolean }) {
  const q = useData<Row[]>('/announcements'); const notifications = useData<Row[]>('/notifications', volunteer); const outbox = useData<Row[]>('/mock-outbox', !volunteer);
  const [tab, setTab] = useState('messages'); const [edit, setEdit] = useState<Row | null | undefined>(); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [preview, setPreview] = useState<Row | null>(null); const [busy, setBusy] = useState(false);
  const filter = useFilter(q.data || [], ['title', 'body']);
  const run = async (path: string, data: Row, describe: (result: Row) => string) => { setBusy(true); setError(''); try { const result = await api<Row>(path, 'POST', data); setMessage(describe(result)); await refresh(); } catch (failure: any) { setError(failure.message); } finally { setBusy(false); } };
  return <><Header title="Announcements" subtitle={volunteer ? 'Updates intended for you and your association community.' : 'Draft messages, publish in-app and preview mock delivery.'}>{!volunteer && <Button onClick={() => setEdit(null)}><Plus size={18} /> Draft announcement</Button>}</Header>{message && <Notice>{message}</Notice>}{error && <Notice type="warning">{error}</Notice>}<Tabs value={tab} onValueChange={setTab} items={[
    { value: 'messages', label: 'Announcements', content: <Panel><Toolbar search={filter.search} onSearch={filter.setSearch}>{!volunteer && <select aria-label="Announcement status" value={filter.status} onChange={event => filter.setStatus(event.target.value)}><option value="">All statuses</option>{['DRAFT', 'PUBLISHED', 'ARCHIVED'].map(status => <option key={status} value={status}>{textStatus(status)}</option>)}</select>}</Toolbar><State query={q}><div className="announcement-list">{filter.paged.map(announcement => { const notification = notifications.data?.find(row => row.announcement_id === announcement.id); return <article className="announcement-card" key={announcement.id}><div className="announcement-heading"><span className="attention-icon indigo"><Megaphone size={22} /></span><div className="flex-grow"><h2>{announcement.title}</h2><p className="small muted">{announcement.audience === 'all' ? 'All member records' : 'Volunteers'} · {announcement.published_at ? `Published ${date(announcement.published_at, true)}` : `Drafted ${date(announcement.created_at)}`}</p></div><Badge status={announcement.status} /></div><p className="announcement-body">{announcement.body}</p><div className="action-row">{!volunteer && announcement.status === 'DRAFT' && <><Button variant="outline" onClick={() => setEdit(announcement)}>Edit draft</Button><Confirm title="Publish this announcement?" description="The content and audience are preserved after publication. Recipients receive an in-app notification and a fictional mock delivery preview." onConfirm={async () => { const result = await api<Row>(`/announcements/${announcement.id}/publish`, 'POST', {}); await refresh(); setMessage(`Published. ${result.queued_recipients} fictional delivery previews queued.`); }}><Button>Publish</Button></Confirm></>}{!volunteer && announcement.status !== 'ARCHIVED' && <Confirm title="Archive this announcement?" description="The publication history is preserved." onConfirm={async () => { await api(`/announcements/${announcement.id}/archive`, 'POST', {}); await refresh(); }}><Button variant="ghost">Archive</Button></Confirm>}{volunteer && notification && !notification.read_at && <Button variant="outline" onClick={() => run(`/notifications/${notification.id}/read`, {}, () => 'Notification marked read.')}><Check size={15} /> Mark read</Button>}{volunteer && notification?.read_at && <Badge status="READ" />}</div></article>; })}{!filter.paged.length && <Empty>No announcements match your search.</Empty>}</div><Pagination count={filter.filtered.length} page={filter.page} setPage={filter.setPage} /></State></Panel> },
    ...(!volunteer ? [{ value: 'outbox', label: 'Mock delivery & reminders', content: <><Panel title="MOCK DELIVERY" icon={Mail}><Notice>Fictional recipients and simulated delivery only. No email is sent.</Notice><div className="action-row"><Button disabled={busy} onClick={() => run('/mock-outbox/run', {}, result => `${result.delivered} simulated deliveries completed; ${result.failed} failed.`)}>Process queued previews</Button><Button variant="outline" disabled={busy} onClick={() => run('/mock-outbox/run', { simulate_failure: true }, result => `${result.failed} queued previews marked as simulated failures.`)}>Simulate failure</Button><Button variant="outline" disabled={busy} onClick={() => run('/jobs/reminders', {}, result => `${result.queued} new renewal reminders queued. Repeated runs skip existing reminders.`)}>Run renewal reminders now</Button></div></Panel><Panel title="Persistent mock outbox"><State query={outbox}><Table rows={outbox.data || []} columns={[{ label: 'Recipient', render: row => <div><strong>{row.recipient_email}</strong><span className="cell-sub">{date(row.created_at, true)}</span></div> }, { label: 'Subject', render: row => row.subject }, { label: 'Status', render: row => <Badge status={row.status} /> }, { label: 'Attempts', render: row => row.attempts }, { label: '', render: row => <div className="action-row"><Button variant="outline" onClick={() => setPreview(row)}>Preview</Button>{row.status === 'FAILED' && <Button variant="ghost" disabled={busy} onClick={() => run(`/mock-outbox/${row.id}/retry`, {}, () => 'Mock delivery queued for retry.')}>Retry</Button>}</div> }]} /></State></Panel></> }] : [])
  ]} /><Modal open={edit !== undefined} onOpenChange={open => !open && setEdit(undefined)} title={edit ? 'Edit announcement draft' : 'Draft announcement'} description="Choose the intended audience before publishing.">{edit !== undefined && <Form initial={edit || { audience: 'volunteers' }} fields={[{ name: 'title', label: 'Title', required: true }, { name: 'audience', label: 'Audience', required: true, options: [{ value: 'volunteers', label: 'Volunteers' }, { value: 'all', label: 'All member records' }] }, { name: 'body', label: 'Message', type: 'textarea', required: true }]} label="Save draft" onSubmit={async values => { await api(edit ? `/announcements/${edit.id}` : '/announcements', edit ? 'PATCH' : 'POST', values); await refresh(); setEdit(undefined); }} />}</Modal><Modal open={!!preview} onOpenChange={open => !open && setPreview(null)} title="MOCK DELIVERY · Preview" description="This is a fictional delivery preview, stored locally.">{preview && <><div className="detail-facts"><div><span>To</span><strong>{preview.recipient_email}</strong></div><div><span>Subject</span><strong>{preview.subject}</strong></div><div><span>Status</span><Badge status={preview.status} /></div></div><p className="announcement-body">{preview.body}</p>{preview.error && <Notice type="warning">{preview.error}</Notice>}</>}</Modal></>;
}
